/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.94
 * Generated at: 2019-05-24 10:18:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.bbs;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class detail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {



String driver="oracle.jdbc.driver.OracleDriver";
String url="jdbc:oracle:thin:@localhost:1521:xe";
String user="hr";
String password="hr";


		Connection conn;
		Statement stmt;
		ResultSet rs;
	
  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/bbs/../templete/footer.jspf", Long.valueOf(1558675790353L));
    _jspx_dependants.put("/bbs/../templete/header.jspf", Long.valueOf(1558680455327L));
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=EUC-KR\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

String path=request.getRequestURI();
int cnt=-2;
for(int i=0; i<path.length(); i++){
	if(path.charAt(i)=='/'){cnt++;}
}
path="./";
for(int j=0; j<cnt; j++){
	path+="../";
}//상대경로 만드는 함수


      out.write("\r\n");
      out.write("\t<table width=\"800\" align=\"center\" border=\"1\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td colspan=\"6\">\r\n");
      out.write("\t\t\t\t<table width=\"100%\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td align=\"right\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\">로그인</a>\r\n");
      out.write("\t\t\t\t\t\t\t/\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\">회원가입</a>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td align=\"center\"><img src=\"");
      out.print(path );
      out.write("/imgs/logo.png\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td width=\"200\"></td>\r\n");
      out.write("\t\t\t<td width=\"100\"><a href=\"");
      out.print(path );
      out.write("\">[HOME]</a></td>\r\n");
      out.write("\t\t\t<td width=\"100\"><a href=\"");
      out.print(path );
      out.write("comming.jsp\">[오시는길]</a></td>\r\n");
      out.write("\t\t\t<td width=\"100\"><a href=\"");
      out.print(path );
      out.write("bbs/list.jsp\">[게 시 판]</a></td>\r\n");
      out.write("\t\t\t<td width=\"100\"><a href=\"#\">[방 명 록]</a></td>\r\n");
      out.write("\t\t\t<td width=\"200\"></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t<td colspan=\"6\">\r\n");
      out.write("\t\t\t<!-- main start -->\r\n");
      out.write("\t\t\t");
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write('\r');
      out.write('\n');

class Row{
	int num;
	String id;
	String sub;
	String content;
	Date nalja;
	
	public String getNalja(){
		String msg=(nalja.getYear()+1900)+"년"
				+(nalja.getMonth()+1)+"월"
				+nalja.getDate()+"일";
		return msg;
	}
}
Row row=new Row();
String param=request.getParameter("idx");
int num=0;
try{
	num=Integer.parseInt(param);
}catch(Exception e){
	response.sendRedirect("list.jsp");
	return;
}

String id="-";
String sub="-";
String content="-";
Date nalja=null;
String sql="select * from bbs03 where num="+num;
Class.forName(driver);
try{
	conn=DriverManager.getConnection(url, user, password);
	stmt=conn.createStatement();
	rs=stmt.executeQuery(sql);
	if(rs.next()){
		row.num=rs.getInt("num");
		row.sub=rs.getString("sub");
		row.content=rs.getString("content");
		row.nalja=rs.getDate("nalja");
		row.id=rs.getString("id");
	}else{
		response.sendRedirect("list.jsp");
		return;
	}
}finally{
	if(rs!=null)rs.close();
	if(stmt!=null)stmt.close();
	if(conn!=null)conn.close();
}


      out.write("\r\n");
      out.write("\t<h1 align=\"center\">상세 페이지</h1>\r\n");
      out.write("\t<table width=80% align=center>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td bgcolor=\"#E2E2E2\" width=100>글번호</td>\r\n");
      out.write("\t\t\t<td>");
      out.print(row.num );
      out.write("</td>\r\n");
      out.write("\t\t\t<td bgcolor=\"#E2E2E2\" width=100>글쓴이</td>\r\n");
      out.write("\t\t\t<td>");
      out.print(row.id );
      out.write("</td>\r\n");
      out.write("\t\t\t<td bgcolor=\"#E2E2E2\" width=100>작성일</td>\r\n");
      out.write("\t\t\t<td>");
      out.print(row.nalja );
      out.write("</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td bgcolor=\"#E2E2E2\">제목</td>\r\n");
      out.write("\t\t\t<td colspan=\"5\">");
      out.print(row.sub );
      out.write("</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td colspan=6><pre>");
      out.print(row.content );
      out.write("</pre></td>\r\n");
      out.write("\t\t</tr> ");
 //pre: pre사이에 있는 내용을 그대로 보내줌-> 엔터에 자동 br변환 
      out.write("\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td colspan=6 bgcolor=\"#BFB9B6\">\r\n");
      out.write("\t\t\t\t<a href=\"edit.jsp?idx=");
      out.print(row.num );
      out.write("\">[수 정]</a>\r\n");
      out.write("\t\t\t\t<a href=\"delete.jsp?idx=");
      out.print(row.num );
      out.write("\">[삭 제]</a>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\t\t<!-- main end -->\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<br><br><br><br>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<td><img align=\"right\" width=70% height=auto alt=\"logo2\" src=\"");
      out.print(path);
      out.write("/imgs/logo2.png\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td colspan=5>비트캠프 서울시 서초구 강남대로 459 (서초동, 백암빌딩)｜ 사업자등록번호 : 214-85-24928<br>\r\n");
      out.write("(주)비트컴퓨터 서초본원 대표이사 : 조현정 / 문의 : 02-3486-9600 / 팩스 : 02-6007-1245<br>\r\n");
      out.write("통신판매업 신고번호 : 제 서초-00098호 / 개인정보보호관리책임자 : 최종진<br>\r\n");
      out.write("Copyright &copy; 비트캠프 All rights reserved.</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
