/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.94
 * Generated at: 2019-05-27 00:38:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.bbs;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import java.util.List;
import java.util.HashMap;
import java.util.Map;
import java.sql.*;

public final class list_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {



String driver="oracle.jdbc.driver.OracleDriver";
String url="jdbc:oracle:thin:@localhost:1521:xe";
String user="hr";
String password="hr";

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/bbs/../templete/footer.jspf", Long.valueOf(1558675790353L));
    _jspx_dependants.put("/bbs/../templete/header.jspf", Long.valueOf(1558917472496L));
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=EUC-KR\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

String path=request.getRequestURI();
int cnt=-2;
for(int i=0; i<path.length(); i++){
	if(path.charAt(i)=='/'){cnt++;}
}
path="./";
for(int j=0; j<cnt; j++){
	path+="../";
}//상대경로 만드는 함수


      out.write("\r\n");
      out.write("\t<table width=\"800\" align=\"center\" border=\"1\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td colspan=\"6\">\r\n");
      out.write("\t\t\t\t<table width=800>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td align=\"right\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\">로그인</a>\r\n");
      out.write("\t\t\t\t\t\t\t/\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\">회원가입</a>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td align=\"center\" bgcolor=#7BD4B4><img src=\"");
      out.print(path );
      out.write("/imgs/logo.png\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td width=\"200\"></td>\r\n");
      out.write("\t\t\t<td width=\"100\"><a href=\"");
      out.print(path );
      out.write("\">[HOME]</a></td>\r\n");
      out.write("\t\t\t<td width=\"100\"><a href=\"");
      out.print(path );
      out.write("comming.jsp\">[오시는길]</a></td>\r\n");
      out.write("\t\t\t<td width=\"100\"><a href=\"");
      out.print(path );
      out.write("bbs/list.jsp\">[게 시 판]</a></td>\r\n");
      out.write("\t\t\t<td width=\"100\"><a href=\"#\">[방 명 록]</a></td>\r\n");
      out.write("\t\t\t<td width=\"200\"></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t<td colspan=\"6\">\r\n");
      out.write("\t\t\t<!-- main start -->\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("\t<h1>게시판 목록</h1>\r\n");
      out.write("\t\r\n");
      out.write("\t<form>\r\n");
      out.write("\t\t<select name=\"limit\">\r\n");
      out.write("\t\t\t<option value=\"10\">10개씩</option>\r\n");
      out.write("\t\t\t<option value=\"25\">25개씩</option>\r\n");
      out.write("\t\t\t<option value=\"50\">50개씩</option>\r\n");
      out.write("\t\t</select>\r\n");
      out.write("\t\t<input type=\"submit\" value=\"보기\">\r\n");
      out.write("\t</form>\r\n");
      out.write("\t<table width=80% border=1 cellspacing=0 align=center>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th width=80>글번호</th>\r\n");
      out.write("\t\t\t<th>제목</th>\r\n");
      out.write("\t\t\t<th width=80>글쓴이</th>\r\n");
      out.write("\t\t\t<th width=80>날짜</th>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t");

		
		String param = request.getParameter("page");
		String param2=request.getParameter("limit");
		if(param ==null) param="1";
		int p = Integer.parseInt(param);
		if(param2==null)param2="10";
		int limit=Integer.parseInt(param2);
		class Rows{
			int num;
			String sub;
			String id;
			java.sql.Date nalja;
		}
		List<Rows> list=new ArrayList<Rows>();
		
		String sql="select * from (select rownum as rn, num, sub, id, nalja from (select * from bbs03 order by num desc)) where rn>="+(((p-1)*limit)+1)+" and rn<="+(((p-1)*limit)+1+(limit-1));
		Class.forName(driver);
		
		Connection conn = null;
		Statement stmt =null;
		ResultSet rs= null;
		
		try{
			conn=DriverManager.getConnection(url, user, password);
			stmt=conn.createStatement();
			rs=stmt.executeQuery(sql);
			while(rs.next()){
				Rows row = new Rows();
				row.num=rs.getInt("num");
				row.sub=rs.getString("sub");
				row.id=rs.getString("id");
				row.nalja=rs.getDate("nalja");
				list.add(row);
			}
		}finally{
			if(rs!=null) rs.close();
			if(stmt!=null) stmt.close();
			if(conn!=null) conn.close();
		}
		
		for(int i=0; i<list.size(); i++){
			Rows row=list.get(i);
		
      out.write("\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>");
      out.print(row.num );
      out.write("</td>\r\n");
      out.write("\t\t\t<td><a href=\"detail.jsp?idx=");
      out.print(row.num);
      out.write('"');
      out.write('>');
      out.print(row.sub );
      out.write("</a></td>\r\n");
      out.write("\t\t\t<td>");
      out.print(row.id );
      out.write("</td>\r\n");
      out.write("\t\t\t<td>");
      out.print(row.nalja.getMonth()+"월"+row.nalja.getDate()+"일" );
      out.write("</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t");

		}
		
      out.write("\r\n");
      out.write("\t</table>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<center>\r\n");
      out.write("\t");

	int total=0;
	sql = "select count(*) as cnt from bbs03 ";
	try{
		conn=DriverManager.getConnection(url, user, password);
		stmt=conn.createStatement();
		rs=stmt.executeQuery(sql);
		if(rs.next())total=rs.getInt("cnt");
	}finally{
		if(stmt!=null)stmt.close();
		if(conn!=null)conn.close();
	}
	
	int start=((p-1)/5)*5;
	int end = total/limit;
	
	if(total%limit!=0){
		end++;
	}
	int end2=end;
	if(start+5<end){
		end=start +5;
	}
	//이전버튼
		if(start>0){
			
      out.write("\r\n");
      out.write("\t\t\t<a href=\"list.jsp?page=");
      out.print(start-1 );
      out.write("&limit=");
      out.print(limit);
      out.write("\">[이전]</a>\r\n");
      out.write("\t\t\t");

		}
	//1~10 버튼
	for(int i=start; i<end; i++){
	
      out.write("\r\n");
      out.write("\t\t<a href=\"list.jsp?page=");
      out.print(i+1);
      out.write("&limit=");
      out.print(limit);
      out.write('"');
      out.write('>');
      out.write('[');
      out.print(i+1 );
      out.write("]</a>\t\r\n");
      out.write("\t");
 
	}
		//다음버튼
		if(end+1<=end2){
		
      out.write("\r\n");
      out.write("\t\t<a href=\"list.jsp?page=");
      out.print(end+1 );
      out.write("&limit=");
      out.print(limit);
      out.write("\">[다음]</a>\r\n");
      out.write("\t\t");
} 
      out.write("\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<a href=\"");
      out.print(path );
      out.write("bbs/add.jsp\">[입력]</a>\r\n");
      out.write("\t</center>\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\t\t<!-- main end -->\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<br><br><br><br>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<td><img align=\"right\" width=70% height=auto alt=\"logo2\" src=\"");
      out.print(path);
      out.write("/imgs/logo2.png\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td colspan=5>비트캠프 서울시 서초구 강남대로 459 (서초동, 백암빌딩)｜ 사업자등록번호 : 214-85-24928<br>\r\n");
      out.write("(주)비트컴퓨터 서초본원 대표이사 : 조현정 / 문의 : 02-3486-9600 / 팩스 : 02-6007-1245<br>\r\n");
      out.write("통신판매업 신고번호 : 제 서초-00098호 / 개인정보보호관리책임자 : 최종진<br>\r\n");
      out.write("Copyright &copy; 비트캠프 All rights reserved.</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
